/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as MarkAttendanceRouteImport } from './routes/mark-attendance'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkAttendanceRoute = MarkAttendanceRouteImport.update({
  id: '/mark-attendance',
  path: '/mark-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/leaves': typeof LeavesRoute
  '/mark-attendance': typeof MarkAttendanceRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/leaves': typeof LeavesRoute
  '/mark-attendance': typeof MarkAttendanceRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/leaves': typeof LeavesRoute
  '/mark-attendance': typeof MarkAttendanceRoute
  '/timetable': typeof TimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/leaves'
    | '/mark-attendance'
    | '/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/leaves'
    | '/mark-attendance'
    | '/timetable'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/leaves'
    | '/mark-attendance'
    | '/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  LeavesRoute: typeof LeavesRoute
  MarkAttendanceRoute: typeof MarkAttendanceRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mark-attendance': {
      id: '/mark-attendance'
      path: '/mark-attendance'
      fullPath: '/mark-attendance'
      preLoaderRoute: typeof MarkAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  LeavesRoute: LeavesRoute,
  MarkAttendanceRoute: MarkAttendanceRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
